import {
  FileText,
  CreditCard,
  DollarSign,
  BarChart3,
  PieChart,
  Wallet,
  Receipt,
  Users,
  TrendingUp,
  Landmark,
  Calendar,
  Clock,
  Percent,
  ShieldCheck,
  Banknote,
  Calculator,
  FileCheck,
  RefreshCcw,
  LineChart,
  Settings,
} from "lucide-react";

export const heroIcons = [
  { Icon: FileText, label: "invoices", pos: "top-30 left-18 float" },
  { Icon: CreditCard, label: "payments", pos: "top-20 right-16 float-2" },
  { Icon: DollarSign, label: "revenue", pos: "top-29 left-62 float-3" },
  { Icon: BarChart3, label: "analytics", pos: "top-12 right-36 float" },
  { Icon: PieChart, label: "reports", pos: "top-37 right-28 float-2" },
  { Icon: Wallet, label: "wallet", pos: "top-73 right-38 float-4" },
  { Icon: Receipt, label: "receipts", pos: "top-44 right-6 float-2" },
  { Icon: Users, label: "customers", pos: "bottom-24 left-24 float-3" },
  { Icon: TrendingUp, label: "growth", pos: "bottom-15 right-30 float-2" },
  { Icon: Landmark, label: "banking", pos: "bottom-32 right-4 float-4" },

  { Icon: Calendar, label: "billing-cycles", pos: "top-13 left-56 float" },
  { Icon: Clock, label: "due-dates", pos: "top-12 right-72 float" },
  { Icon: Percent, label: "taxes-discounts", pos: "top-60 right-22 float-2" },
  {
    Icon: ShieldCheck,
    label: "secure-payments",
    pos: "top-32 left-42 float-4",
  },
  { Icon: Banknote, label: "cash-flow", pos: "bottom-52 right-44 float" },
  {
    Icon: Calculator,
    label: "invoice-totals",
    pos: "bottom-60 left-17 float-4",
  },
  {
    Icon: FileCheck,
    label: "approved-invoices",
    pos: "bottom-42 left-28 float-3",
  },
  {
    Icon: RefreshCcw,
    label: "recurring-invoices",
    pos: "top-72 right-58 float-4",
  },
  {
    Icon: LineChart,
    label: "financial-trends",
    pos: "bottom-16 right-58 float",
  },
  {
    Icon: Settings,
    label: "business-settings",
    pos: "bottom-54 right-64 float",
  },
];
