import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { QueryProvider } from "@/providers/query-provider";

import { ThemeProvider as NextThemeProvider, useTheme } from "next-themes";
import ThemeDataProvider from "@/context/theme-data-provider";

import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        cz-shortcut-listen="true"
      >
        <QueryProvider>
          <NextThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ThemeDataProvider>
              <div className="w-full">{children}</div>
              <Toaster />
            </ThemeDataProvider>
          </NextThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}

// TODO: Rename all page.tsx files and refactor code
// TODO: lib folder refactoring
// TODO: README file
// TODO: prisma seed file
// TODO: env file & appName & To Email
// TODO: Email From (Resend) / Production
// TODO: Email to (Reset Password + Verification Email + OTP) / Production
