export const labels = {
  customer_name: "Customer Name",
  issuedAt: "Issued At",
  dueAt: "Due At",
  totalAsNumber: "Total",
  createdBy_name: "Created By",
  companyName: "Company",
  taxNumber: "Tax Number",
  priceAsNumber: "Price",
  createdAt: "Created At",
  dueDateAsString: "Due At",
  _count_invoices: "Invoices Count",
  _count_products: "Products Count",
  _count_Payments: "Payments Count",
  emailVerified: "Email Verified",
  invoice_status: "status",
};
