import type { Metadata } from "next";

import { authIsRequired } from "@/lib/auth-utils";

import { AppSidebar } from "@/components/navigation/app-sidebar";
import { ModeToggle } from "@/components/theme/mode-toggle";
import { ThemeColorToggle } from "@/components/theme/theme-color-toggle";
import AuthenticationToggle from "@/components/authentication-toggle";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
  breadcrumb,
}: Readonly<{
  children: React.ReactNode;
  breadcrumb: React.ReactNode;
}>) {
  await authIsRequired();

  return (
    <SidebarProvider>
      <AppSidebar />

      <div className="w-full mx-6">
        <div className="flex items-center gap-4 py-2 border-b">
          <SidebarTrigger className="cursor-pointer" />
          {breadcrumb}
          <div className="ml-auto flex items-center gap-4">
            <ThemeColorToggle />
            <ModeToggle />
            <AuthenticationToggle />
          </div>
        </div>
        {children}
      </div>
    </SidebarProvider>
  );
}
